server:
    port: 8090
spring:
    application:
        name: agent-gateway
    cloud:
        consul:
#            host: consul
            host: localhost
            discovery:
                prefer-ip-address: true
eureka:
    instance:
        hostname: agent-gateway
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://discovery:9000/eureka/

gateway:
    platformId: SemanticCloud
    mainPort: 10099
    mainHost: jadeplatform
    containerName: gateway
    localhost: localhost
    localPort: 10100
    services: jade.core.event.NotificationService

