server:
    port: 8020
spring:
    application:
        name: semantic-engine
    cloud:
        consul:
            host: localhost
            discovery:
                prefer-ip-address: true
eureka:
    instance:
        hostname: semantic-engine
        preferIpAddress: true
    client:
        serviceUrl:
            defaultZone: http://discovery:9000/eureka/

jena:
    baseOntology: https://semanticcloud.github.io/Ontology/cloud.owl
    ignorePropsWithNoDomain: true
    localMappings:
        "http://semantic-cloud.org/Cloud": file:/opt/SemanticCloud/cloud.owl
