server:
    port: 8020
spring:
    application:
        name: semantic-engine
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9000/eureka/

jena:
    baseOntology: file:/home/malagus/workspace/master-thesis/Ontologia/cloud.owl
    ignorePropsWithNoDomain: true
    localMappings:
        "http://semantic-cloud.org/Cloud": file:/home/malagus/workspace/master-thesis/Ontologia/cloud.owl

