server:
    port: 8080
debug:
spring:
    application:
        name: gateway
security:
    user:
        password: none
eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:9000/eureka/
zuul:
    routes:
        dashboard: /**
