server:
  port: 8888

eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:9000/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SemanticCloud/SemanticCloud-Config.git
